_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/co_dino_r50.yml',
  '_base_/co_detr_reader.yml',
]

weights: output/co_dino_r50_5scale_1x_coco/model_final
find_unused_parameters: True
log_iter: 5
