_BASE_: [
  '../datasets/coco_instance.yml',
  '../runtime.yml',
  './_base_/optimizer_80e.yml',
  './_base_/ppyoloe_plus_seg_crn.yml',
  './_base_/ppyoloe_plus_seg_reader.yml',
]

log_iter: 10
snapshot_epoch: 5
weights: output/ppyoloe_plus_seg_crn_l_80e_coco/model_final


pretrain_weights: https://paddledet.bj.bcebos.com/models/ppyoloe_plus_crn_l_80e_coco.pdparams
depth_mult: 1.0
width_mult: 1.0
